fix: add propose transfer functions
orcaprotocol/orca-sdk pull request #30
Opened 2022-03-24 19:25 UTC by 0xGrapefruit

2022-03-28 13:47 UTC, jtlacci commented on src/Pod.ts
> +    const signerAddress = await signer.getAddress();
and a `!isMember` for the to address ?

2022-03-28 13:51 UTC, jtlacci commented on src/Pod.ts
> +    // Tells MemberToken to mint a new token for this pod to newMember.
```js
// Tells MemberToken to transfer token for this pod from subpod.safe to checkedAddress.
```

2022-03-28 14:59 UTC, jtlacci requested changes
feel like maybe we should figure out a way to do some more stateful integration tests

2022-03-28 14:59 UTC, jtlacci commented on src/Pod.ts
> +      1,
should be `this.id`

2022-03-29 17:12 UTC, 0xGrapefruit commented on src/Pod.ts
> +      signerAddress,
Good catch

2022-03-31 19:55 UTC, jtlacci approved these changes

2022-03-31 19:56 UTC, merged