feat: pod create functions
orcaprotocol/orca-sdk pull request #65
Opened 2022-07-15 14:43 UTC by 0xGrapefruit

2022-07-15 14:48 UTC, DanThomp507 approved these changes

2022-07-16 23:58 UTC, jtlacci requested changes

2022-07-16 23:58 UTC, jtlacci commented on src/pod-create.ts
> +    const Controller = getContract('ControllerLatest', signer);
we can't rely on them having enabled latest module, we will probably need to figure out which module they have enabled

2022-07-16 23:59 UTC, jtlacci reviewed
are we adding a function to create the pod image

2022-07-18 15:13 UTC, jtlacci approved these changes
Looks great will

2022-07-18 15:13 UTC, jtlacci commented on src/config.ts
> +  etherscanApiKey: '2WNX6IRB7FI49FW9BPY2W8YE5XGBCDQCRB',
we shouldn't be commiting this

2022-07-20 21:17 UTC, merged